import 'package:flutter/material.dart';
import 'package:qr_flutter/qr_flutter.dart';

/// BorrowQrDialog generates and displays a QR code for book borrowing transactions.
/// The QR code encodes borrowing data and is scanned by the librarian to finalize the transaction.
/// Flow: User creates a borrow record → Dialog displays QR code → Librarian scans → Backend records transaction
class BorrowQrDialog extends StatelessWidget {
  const BorrowQrDialog({
    super.key,
    required this.qrData, // Encoded transaction/borrow data (generated by backend)
    required this.bookTitle,
    required this.studentName,
    this.title = 'Borrow QR code',
    this.instruction =
        'Show this code to the librarian. The borrow record is saved only after the QR scan is successful.',
  });

  final String qrData; // QR data passed from parent widget
  final String bookTitle;
  final String studentName;
  final String title;
  final String instruction;

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: SingleChildScrollView(
        padding: const EdgeInsets.fromLTRB(24, 18, 24, 24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Expanded(
                  child: Text(
                    title,
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                    style: TextStyle(
                      color: Color(0xFF121926),
                      fontSize: 20,
                      fontWeight: FontWeight.w800,
                      letterSpacing: 0,
                    ),
                  ),
                ),
                _QrIconButton(
                  onTap: () => Navigator.pop(context),
                  child: const Icon(
                    Icons.close_rounded,
                    color: Color(0xFF121926),
                    size: 24,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 14),
            Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
              decoration: BoxDecoration(
                color: const Color(0xFF2BA6A3).withValues(alpha: 0.16),
                borderRadius: BorderRadius.circular(18),
                border: Border.all(color: const Color(0xFF2BA6A3)),
              ),
              child: Text(
                instruction,
                style: TextStyle(
                  color: Color(0xFF197C79),
                  fontSize: 13,
                  height: 1.35,
                  fontWeight: FontWeight.w700,
                  letterSpacing: 0,
                ),
              ),
            ),
            const SizedBox(height: 18),
            Center(
              child: LayoutBuilder(
                builder: (context, constraints) {
                  // Responsive sizing: QR code scales based on screen width
                  // If screen < 280px, use full width; otherwise cap at 280px max
                  final qrSize = constraints.maxWidth < 280
                      ? constraints.maxWidth
                      : 280.0;

                  return Container(
                    padding: const EdgeInsets.all(14),
                    decoration: BoxDecoration(
                      color: const Color(0xFFF5F7FA),
                      borderRadius: BorderRadius.circular(24),
                    ),
                    child: Container(
                      padding: const EdgeInsets.all(14),
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(18),
                        border: Border.all(
                          color: const Color(0xFF2BA6A3),
                          width: 1.5,
                        ),
                        boxShadow: [
                          BoxShadow(
                            color: Colors.black.withValues(alpha: 0.08),
                            blurRadius: 14,
                            offset: const Offset(0, 7),
                          ),
                        ],
                      ),
                      child: SizedBox.square(
                        dimension: qrSize,
                        // QrImageView: generates QR code from qrData
                        // Uses auto version detection to fit data efficiently
                        child: QrImageView(
                          data: qrData, // Backend-generated transaction data
                          version: QrVersions.auto,
                          backgroundColor: Colors.white,
                          eyeStyle: const QrEyeStyle(
                            eyeShape: QrEyeShape.square,
                            color: Colors.black,
                          ),
                          dataModuleStyle: const QrDataModuleStyle(
                            dataModuleShape: QrDataModuleShape.square,
                            color: Colors.black,
                          ),
                          padding: EdgeInsets.zero,
                        ),
                      ),
                    ),
                  );
                },
              ),
            ),
            const SizedBox(height: 18),
            Wrap(
              spacing: 10,
              runSpacing: 10,
              children: [
                _InfoChip(
                  label: 'Book',
                  value: bookTitle,
                  icon: Icons.menu_book_rounded,
                ),
                _InfoChip(
                  label: 'Student',
                  value: studentName,
                  icon: Icons.person_rounded,
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

/// _InfoChip displays metadata about the borrow transaction (book title, student name)
/// Receives data from parent and formats it for display
class _InfoChip extends StatelessWidget {
  const _InfoChip({
    required this.label,
    required this.value,
    required this.icon,
  });

  final String label;
  final String value;
  final IconData icon;

  @override
  Widget build(BuildContext context) {
    return Container(
      constraints: const BoxConstraints(minHeight: 54),
      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 9),
      decoration: BoxDecoration(
        color: const Color(0xFFF5F7FA),
        borderRadius: BorderRadius.circular(18),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 19, color: const Color(0xFF2BA6A3)),
          const SizedBox(width: 10),
          ConstrainedBox(
            constraints: BoxConstraints(
              // Get screen width and calculate max width for text (prevents overflow)
              maxWidth: MediaQuery.sizeOf(context).width - 120,
            ),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  label,
                  style: const TextStyle(
                    color: Color(0xFF5F6675),
                    fontSize: 11,
                    fontWeight: FontWeight.w600,
                    letterSpacing: 0,
                  ),
                ),
                const SizedBox(height: 2),
                Text(
                  value,
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                  style: const TextStyle(
                    color: Color(0xFF121926),
                    fontSize: 13,
                    height: 1.2,
                    fontWeight: FontWeight.w800,
                    letterSpacing: 0,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

/// _QrIconButton is a custom StatefulWidget that creates an animated icon button
/// with a scale animation when pressed. Used for the close button in the dialog.
/// _QrIconButton is a custom StatefulWidget for the close button
/// Manages button press state and triggers callback when tapped
class _QrIconButton extends StatefulWidget {
  const _QrIconButton({
    required this.child,
    required this.onTap, // Callback executed when button is pressed
  });

  final Widget child;
  final VoidCallback onTap;

  @override
  State<_QrIconButton> createState() => _QrIconButtonState();
}

/// State management for _QrIconButton
/// Tracks pressed state to trigger scale animation and execute callback
class _QrIconButtonState extends State<_QrIconButton> {
  // Track if button is currently pressed (for animation state)
  bool _pressed = false;

  /// Updates pressed state and rebuilds widget if changed
  /// Early exit if state hasn't changed (prevents unnecessary rebuilds)
  void _setPressed(bool value) {
    if (_pressed == value) {
      return;
    }
    // setState triggers rebuild with new animation scale
    setState(() => _pressed = value);
  }

  @override
  Widget build(BuildContext context) {
    // GestureDetector captures tap events and updates button state
    return GestureDetector(
      onTap: widget.onTap, // Execute callback when tap completes
      onTapDown: (_) => _setPressed(true), // Mark pressed when finger touches
      onTapCancel: () => _setPressed(false), // Mark unpressed if tap canceled
      onTapUp: (_) => _setPressed(false), // Mark unpressed when finger lifts
      behavior: HitTestBehavior.opaque,
      child: AnimatedScale(
        scale: _pressed ? 0.94 : 1, // Scale changes based on pressed state
        duration: const Duration(milliseconds: 130),
        curve: Curves.easeOutCubic,
        child: SizedBox.square(
          dimension: 44,
          child: Center(child: widget.child),
        ),
      ),
    );
  }
}
